version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - 5432:5432
